// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCKkAXU2Q-Mjl6z-ZHaXLKQWp7M12IlUA',
    appId: '1:560215788845:web:bff7098821e519626897a4',
    messagingSenderId: '560215788845',
    projectId: 'road-damage-detection-2dd1f',
    authDomain: 'road-damage-detection-2dd1f.firebaseapp.com',
    storageBucket: 'road-damage-detection-2dd1f.appspot.com',
    measurementId: 'G-26GQ6TWSXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSat13mw70bhO9xW9B5kG9pixW_wHFGM',
    appId: '1:560215788845:android:d3ef218e9066fcfb6897a4',
    messagingSenderId: '560215788845',
    projectId: 'road-damage-detection-2dd1f',
    storageBucket: 'road-damage-detection-2dd1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuWoKzN-d0enDfWPn6bi-S-q9EfN9JfeY',
    appId: '1:560215788845:ios:321b2cd259a5a8ec6897a4',
    messagingSenderId: '560215788845',
    projectId: 'road-damage-detection-2dd1f',
    storageBucket: 'road-damage-detection-2dd1f.appspot.com',
    iosBundleId: 'app.rdd.roadDamageDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuWoKzN-d0enDfWPn6bi-S-q9EfN9JfeY',
    appId: '1:560215788845:ios:321b2cd259a5a8ec6897a4',
    messagingSenderId: '560215788845',
    projectId: 'road-damage-detection-2dd1f',
    storageBucket: 'road-damage-detection-2dd1f.appspot.com',
    iosBundleId: 'app.rdd.roadDamageDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCKkAXU2Q-Mjl6z-ZHaXLKQWp7M12IlUA',
    appId: '1:560215788845:web:608b5848ab82de4d6897a4',
    messagingSenderId: '560215788845',
    projectId: 'road-damage-detection-2dd1f',
    authDomain: 'road-damage-detection-2dd1f.firebaseapp.com',
    storageBucket: 'road-damage-detection-2dd1f.appspot.com',
    measurementId: 'G-LN63WEYXB3',
  );
}
